model:
  name: deepar
  params:
    freq: B
    context_length: null
    prediction_length: null
    num_layers: 2
    hidden_size: 40
    lr: 1.0e-3
    weight_decay: 1.0e-8
    dropout_rate: 0.1
    patience: 10
    num_feat_dynamic_real: 0
    num_feat_static_cat: 0
    num_feat_static_real: 0
    cardinality: null
    embedding_dimension: null
    distr_output: student_t
    scaling: true
    default_scale: null
    lags_seq: null
    num_parallel_samples: 100
    batch_size: 32
    num_batches_per_epoch: 50
    nonnegative_pred_samples: false
    max_epochs: 100
    gradient_clip_val: 10.0
    use_time_features: true
    use_asset_static_cat: false
    device: auto

